### ISSUE TITLE
Not really an issue, just wanted to tell you how much I love this

### ISSUE THREAD

**Issue by mkmozgawa** [faissaloo/telegram-micro#1]
Thank you for working on it. I did some J2ME stuff recently and will be happy to help out with some tasks, either directly with Java or something from the "related" section. Cheers!

**Comment by faissaloo** [comment]
Much appreciated! If you (or other people) want to help out I'll make a project board and put some stuff that needs work on there that I wouldn't otherwise get around to. For now most of the stuff is very foundational so there will probably be a decent amount of code churn.  
Feel free to continue using the issues as a discussion forum, since it does the job.

**Comment by faissaloo** [comment]
Ok, I've created https://github.com/faissaloo/telegram-micro/projects/1 and invited you to collaborate, could you let me know if you can move cards around on the board?  
Also, let me know if you need help getting context around things or setting up your environment
