### ISSUE TITLE
Proposal: include prebuilt J2ME JARs -- it's TOO HARD TO COMPILE UNDER WSL!!

### ISSUE THREAD

**Issue by santi100a** [faissaloo/telegram-micro#8]
Hello, @faissaloo! I have a little proposal for you -- can you **please** include pre-compiled JARs?
It's very hard to compile under WSL.
`preverify` fails very weirdly when I try to build -- it says `1: Syntax error: "(" unexpected`.
Run complains about `sublime.so`.
I dunno what to do... Please help me!

**Comment by faissaloo** [comment]
Hello, this software is currently a proof of concept. It has no meaningful GUI other than debug messages and is unusable for actual communication, so it is not useful for us to provide pre-compiled JARs at this stage, since anyone who has an interest in working on it should be able to follow the instructions to build the project.

Furthermore, you will not be able to use WSL to build this project. You will either need to figure out how to get Ktoolbar running on modern Windows, or use Linux and follow the instructions (you could also try Windows XP if you really want but that feels a bit pointless).

**Comment by santi100a** [comment]
But you're working on a UI, right?

**Comment by faissaloo** [comment]
I'm not actively working on this atm, but yes the idea is that there will be a UI eventually. UI is relatively straightfoward, all of the complexities are in the protocol.
